### ISSUE TITLE
Unable to install Chocolatey from local repo using Ansible

### ISSUE THREAD

**Issue by matt-95** [chocolatey/choco#2897]
### What You Are Seeing?
Getting Error Msg -

"msg": "Failed to find choco.exe, make sure it is added to the PATH or the env var 'ChocolateyInstall' is set",
  "warnings": [
    "Chocolatey was missing from this system, so it was installed during this task run."
  ],

### What is Expected?

Chocolatey to be downloaded and installed without an issues.

### How Did You Get This To Happen? (Steps to Reproduce)
Playbook - 
tasks:
    - name: Ensure Chocolatey itself is installed and use internal repo as source for bootstrap script
      chocolatey.chocolatey.win_chocolatey:
        name: chocolatey
        state: present
        source: https://myrepo/repository/choco-install/ChocolateyInstall.ps1
        source_username: username
        source_password: password

NOTE: We may be unable to troubleshoot / respond to issues without reproducible
steps. If you do not complete this section there is a high chance your issue
may be closed.

### System Details

* OS Build (In PowerShell run `[System.Environment]::OSVersion.version.tostring()`):
* Windows PowerShell version (Run: `$PSVersionTable`):
* Chocolatey version (Run `choco --version`):

### Output Log

<details>
<summary>Full Log Output</summary>

<p>

~~~sh
IF YOUR LOG CONTENT IS SHORT, PLACE IT HERE - WE NEED _ALL_ DETAILED OUTPUT BASED ON THE ABOVE TO BE ABLE TO PROVIDE SUPPORT (YOU WILL FIND THAT IN THE $env:ChocolateyInstall\logs\chocolatey.log between the `=====`)
IF YOUR LOG CONTENT IS LONG, PLEASE LINK TO A GIST (see https://docs.github.com/en/github/writing-on-github/editing-and-sharing-content-with-gists/creating-gists)
~~~

</p>

</details>

**Comment by JPRuskin** [comment]
I think for using a custom-location bootstrap script, you need to use the property `bootstrap_script` rather than `source` - or provide the generic repository URL as `source`, e.g.:

```
- name: Ensure Chocolatey itself is installed and use internal repo as source for bootstrap script
  win_chocolatey:
    name: chocolatey
    source: http://someserver/chocolatey

- name: Ensure Chocolatey itself is installed, using a specific bootstrap script
  win_chocolatey:
    name: chocolatey
    bootstrap_script: https://internal-web-server/files/custom-chocolatey-install.ps1
```
