### ISSUE TITLE
refreshenv no longer works in 2.0.0 when called via Ansible

### ISSUE THREAD

**Issue by nre-ableton** [chocolatey/choco#3188]
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my problem.
- [X] I have verified this is not an issue for a specific package.
- [X] I have verified this issue is not security related.

### What You Are Seeing?

As of chocolatey 2.0.0, when our Ansible playbooks call `refreshenv.cmd` it returns `RefreshEnv.cmd does not work when run from this process. If you're in PowerShell, please 'Import-Module $env:ChocolateyInstall\\helpers\\chocolateyProfile.psm1' and try again.`.

This occurs when called with the `win_command`, `win_shell`, or `win_powershell` modules, and also occurs when importing the module, like so:

```yaml
- name: Refresh Windows environment
  ansible.windows.win_powershell:
    script: |
      Import-Module $env:ChocolateyInstall\helpers\chocolateyProfile.psm1
      refreshenv.cmd
```

This seems to have been introduced by https://github.com/chocolatey/choco/commit/abd389acb3d991ae9849a8d44deb6f3cd55ed52f (in https://github.com/chocolatey/choco/issues/1392).

### What is Expected?

`refreshenv` runs without errors.

### How Did You Get This To Happen?

See the above Ansible task.

### System Details

* Operating System: Windows 10
* Chocolatey CLI Version: 2.0.0

### Installed Packages

```bash
N/A
```

### Output Log

```bash
N/A
```
